server.port=8081

spring.application.name=data-api
spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://localhost:5432/appdb}
spring.datasource.username=${POSTGRES_USER:appuser}
spring.datasource.password=${POSTGRES_PASSWORD:apppass}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view: false
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

app.internal-token: ${INTERNAL_TOKEN:dev-internal-token}
