server.port=8080
spring.application.name=auth-api
spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://localhost:5432/appdb}
spring.datasource.username=${POSTGRES_USER:appuser}
spring.datasource.password=${POSTGRES_PASSWORD:apppass}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view: false
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

app.jwt-secret: ${JWT_SECRET:change-me-change-me-change-me-change-me}
app.internal-token: ${INTERNAL_TOKEN:dev-internal-token}
app.data-api-url: ${DATA_API_URL:http://data-api:8081}